# Generated by Django 2.0 on 2018-09-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='breif',
        ),
    ]
