# Generated by Django 2.0 on 2018-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technology',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
