# Generated by Django 2.0 on 2019-06-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_post_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
